{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "NONE",
   "body" : "### Motivation\n\nI'm getting a strange error running tests under `/src/test/functional/` with the following error:\r\n\r\n```sh\r\nTemporary test directory at /tmp/test_runner_â¿_ð_20220504_123152\r\nRunning Unit Tests for Test Framework Modules\r\n..........\r\n----------------------------------------------------------------------\r\nRan 10 tests in 0.614s\r\n\r\nOK\r\nTraceback (most recent call last):\r\n  File \"/usr/src/bitcoin/test/functional/create_cache.py\", line 27, in <module>\r\n    CreateCache().main()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 156, in main\r\n    exit_code = self.shutdown()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 311, in shutdown\r\n    self.stop_nodes()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 567, in stop_nodes\r\n    node.stop_node(wait=wait, wait_until_stopped=False)\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_node.py\", line 336, in stop_node\r\n    self.stop(wait=wait)\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_node.py\", line 184, in __getattr__\r\n    assert self.rpc_connected and self.rpc is not None, self._node_msg(\"Error: no RPC connection\")\r\nAssertionError: [node 0] Error: no RPC connection\r\n2022-05-04T19:31:53.315000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_â¿_ð_20220504_123152/cache\r\n2022-05-04T19:31:56.079000Z TestFramework (ERROR): Unexpected exception caught during testing\r\nTraceback (most recent call last):\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 132, in main\r\n    self.setup()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 294, in setup\r\n    self.setup_chain()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 385, in setup_chain\r\n    self._initialize_chain()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 777, in _initialize_chain\r\n    self.start_node(CACHE_NODE_ID)\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_framework.py\", line 534, in start_node\r\n    node.wait_for_rpc_connection()\r\n  File \"/usr/src/bitcoin/test/functional/test_framework/test_node.py\", line 225, in wait_for_rpc_connection\r\n    raise FailedToStartError(self._node_msg(\r\ntest_framework.test_node.FailedToStartError: [node 0] bitcoind exited with status 3 during initialization\r\n2022-05-04T19:31:56.133000Z TestFramework (INFO): Stopping nodes\r\n[node 0] Cleaning up leftover process\r\nTraceback (most recent call last):\r\n  File \"test/functional/test_runner.py\", line 832, in <module>\r\n    main()\r\n  File \"test/functional/test_runner.py\", line 471, in main\r\n    run_tests(\r\n  File \"test/functional/test_runner.py\", line 525, in run_tests\r\n    subprocess.check_output([sys.executable, tests_dir + 'create_cache.py'] + flags + [\"--tmpdir=%s/cache\" % tmpdir])\r\n  File \"/usr/lib/python3.8/subprocess.py\", line 415, in check_output\r\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\r\n  File \"/usr/lib/python3.8/subprocess.py\", line 516, in run\r\n    raise CalledProcessError(retcode, process.args,\r\nsubprocess.CalledProcessError: Command '['/usr/bin/python3', '/usr/src/bitcoin/test/functional/create_cache.py', '--cachedir=/usr/src/bitcoin/test/cache', '--configfile=/usr/src/bitcoin/test/functional/../config.ini', '--tmpdir=/tmp/test_runner_â¿_ð_20220504_123152/cache']' returned non-zero exit status 1.\r\n`\\\r\n```\r\n\r\nany pointers are highly appreciated\n\n### Possible solution\n\n_No response_\n\n### Useful Skills\n\n- RPC/P2P layer\r\n- Debugging\r\n- overall understanding of Bitcoin Core\n\n### Guidance for new contributors\n\nWant to work on this issue?\r\n\r\nFor guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.\r\n",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 0,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28000/comments",
   "created_at" : "2023-06-29T11:58:27Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28000/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/28000",
   "id" : 1780679318,
   "labels" : [
      {
         "color" : "c2e0c6",
         "default" : true,
         "description" : null,
         "id" : 349312277,
         "name" : "good first issue",
         "node_id" : "MDU6TGFiZWwzNDkzMTIyNzc=",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/good%20first%20issue"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28000/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "I_kwDOABII585qIwKW",
   "number" : 28000,
   "performed_via_github_app" : null,
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28000/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28000/timeline",
   "title" : "Error: no RPC connection\" when trying to run Bitcoin Core functional tests",
   "updated_at" : "2023-06-29T11:58:27Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28000",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/37052032?v=4",
      "events_url" : "https://api.github.com/users/naftalimurgor/events{/privacy}",
      "followers_url" : "https://api.github.com/users/naftalimurgor/followers",
      "following_url" : "https://api.github.com/users/naftalimurgor/following{/other_user}",
      "gists_url" : "https://api.github.com/users/naftalimurgor/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/naftalimurgor",
      "id" : 37052032,
      "login" : "naftalimurgor",
      "node_id" : "MDQ6VXNlcjM3MDUyMDMy",
      "organizations_url" : "https://api.github.com/users/naftalimurgor/orgs",
      "received_events_url" : "https://api.github.com/users/naftalimurgor/received_events",
      "repos_url" : "https://api.github.com/users/naftalimurgor/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/naftalimurgor/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/naftalimurgor/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/naftalimurgor"
   }
}
