{
   "assignee" : null,
   "assignees" : [],
   "body" : "[My block database became corrupt](https://github.com/bitcoin/bitcoin/issues/8522):\r\n\r\n![image](https://cloud.githubusercontent.com/assets/12032350/17698822/8c237694-63bd-11e6-910a-ae53a0ae9640.png)\r\n\r\nAfter clicking OK I get:\r\n\r\n![image](https://cloud.githubusercontent.com/assets/12032350/17699378/b084109a-63c0-11e6-9c52-20a62ab94576.png)\r\n\r\nWhich appears to be a bug. When I now click OK Bitcoin Core crashes:\r\n\r\n![image](https://cloud.githubusercontent.com/assets/12032350/17699419/db2c461e-63c0-11e6-9f8e-d4601b973906.png)\r\n\r\nAfter restarting it I get:\r\n\r\n![image](https://cloud.githubusercontent.com/assets/12032350/17699436/effaace8-63c0-11e6-81ce-c5e8e61458f0.png)\r\n\r\nAt this point nothing changes when I restart again.\r\n\r\nThe log says:\r\n\r\n2016-08-16 12:52:42 Bitcoin version v0.12.1 (2016-04-11 13:01:43 +0200)\r\n2016-08-16 12:52:42 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1\r\n2016-08-16 12:52:43 GUI: \"registerShutdownBlockReason: Successfully registered: Bitcoin Core didn't yet exit safely...\"\r\n2016-08-16 12:52:44 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)\r\n2016-08-16 12:52:44 Default data directory C:\\Users\\x\\AppData\\Roaming\\Bitcoin\r\n2016-08-16 12:52:44 Using data directory C:\\Users\\x\\AppData\\Roaming\\Bitcoin\r\n2016-08-16 12:52:44 Using config file C:\\Users\\x\\AppData\\Roaming\\Bitcoin\\bitcoin.conf\r\n2016-08-16 12:52:44 Using at most 125 connections (2048 file descriptors available)\r\n2016-08-16 12:52:44 Using 8 threads for script verification\r\n2016-08-16 12:52:44 scheduler thread start\r\n2016-08-16 12:52:44 HTTP: creating work queue of depth 16\r\n2016-08-16 12:52:44 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.\r\n2016-08-16 12:52:44 HTTP: starting 4 worker threads\r\n2016-08-16 12:52:44 Using wallet wallet.dat\r\n2016-08-16 12:52:44 init message: Verifying wallet...\r\n2016-08-16 12:52:44 CDBEnv::Open: LogDir=C:\\Users\\x\\AppData\\Roaming\\Bitcoin\\database ErrorFile=C:\\Users\\x\\AppData\\Roaming\\Bitcoin\\db.log\r\n2016-08-16 12:52:44 Cache configuration:\r\n2016-08-16 12:52:44 * Using 128.0MiB for block index database\r\n2016-08-16 12:52:44 * Using 232.0MiB for chain state database\r\n2016-08-16 12:52:44 * Using 664.0MiB for in-memory UTXO set\r\n2016-08-16 12:52:44 init message: Loading block index...\r\n2016-08-16 12:52:44 Opening LevelDB in C:\\Users\\x\\AppData\\Roaming\\Bitcoin\\blocks\\index\r\n2016-08-16 12:52:44 Opened LevelDB successfully\r\n2016-08-16 12:52:44 Using obfuscation key for C:\\Users\\x\\AppData\\Roaming\\Bitcoin\\blocks\\index: 0000000000000000\r\n2016-08-16 12:52:44 Opening LevelDB in C:\\Users\\x\\AppData\\Roaming\\Bitcoin\\chainstate\r\n2016-08-16 12:52:44 Opened LevelDB successfully\r\n2016-08-16 12:52:44 Using obfuscation key for C:\\Users\\x\\AppData\\Roaming\\Bitcoin\\chainstate: ceb7ff593b2a09a4\r\n2016-08-16 12:52:44 LoadBlockIndexDB: last block file = 0\r\n2016-08-16 12:52:44 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=0, size=0, heights=0...0, time=1970-01-01...1970-01-01)\r\n2016-08-16 12:52:44 Checking all blk files are present...\r\n2016-08-16 12:52:44 LoadBlockIndexDB: transaction index enabled\r\n2016-08-16 12:52:44 Initializing databases...\r\n2016-08-16 12:52:44 Pre-allocating up to position 0x1000000 in blk00000.dat\r\n\r\nHope this helps find the problem.\r\n\r\nI now delete `chainstate` and `database` and `db.log`. The app can now start and syncs with the network. For some reason it does not find the blocks that are still on disk (I did not touch the blocks folder when deleting files). Something about them must have gotten corrupted previously (bug?). I would have liked if I was warned that the existing blocks could not be used instead of silently ignoring them (potential improvement).\r\n",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 0,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8523/comments",
   "created_at" : "2016-08-16T12:57:04Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8523/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/8523",
   "id" : 171401540,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8523/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "number" : 8523,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "title" : "Rebuilding block database after corruption behaves strangely",
   "updated_at" : "2016-08-16T12:58:38Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8523",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/12032350?v=3",
      "events_url" : "https://api.github.com/users/GSPP/events{/privacy}",
      "followers_url" : "https://api.github.com/users/GSPP/followers",
      "following_url" : "https://api.github.com/users/GSPP/following{/other_user}",
      "gists_url" : "https://api.github.com/users/GSPP/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/GSPP",
      "id" : 12032350,
      "login" : "GSPP",
      "organizations_url" : "https://api.github.com/users/GSPP/orgs",
      "received_events_url" : "https://api.github.com/users/GSPP/received_events",
      "repos_url" : "https://api.github.com/users/GSPP/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/GSPP/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/GSPP/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/GSPP"
   }
}
