{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "After #17211 was merged, there have been a few intermittent test failures in `wallet_send.py`, `rpc_fundrawtransaction.py`, and `rpc_psbt.py`\r\n\r\nI believe all these failures are due to these missing `sync_all()`s",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 7,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23200/comments",
   "created_at" : "2021-10-05T22:48:12Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23200/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/23200",
   "id" : 1016994476,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23200/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII584suutG",
   "number" : 23200,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/23200.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/23200",
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/23200.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/23200"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23200/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23200/timeline",
   "title" : "Fix intermittent failure in wallet_send.py and rpc_fundrawtransaction.py",
   "updated_at" : "2021-10-05T23:55:07Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23200",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/3211283?v=4",
      "events_url" : "https://api.github.com/users/meshcollider/events{/privacy}",
      "followers_url" : "https://api.github.com/users/meshcollider/followers",
      "following_url" : "https://api.github.com/users/meshcollider/following{/other_user}",
      "gists_url" : "https://api.github.com/users/meshcollider/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/meshcollider",
      "id" : 3211283,
      "login" : "meshcollider",
      "node_id" : "MDQ6VXNlcjMyMTEyODM=",
      "organizations_url" : "https://api.github.com/users/meshcollider/orgs",
      "received_events_url" : "https://api.github.com/users/meshcollider/received_events",
      "repos_url" : "https://api.github.com/users/meshcollider/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/meshcollider/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/meshcollider/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/meshcollider"
   }
}
